---
version: "3"
services:
  web:
    build:
      context: .
    restart: always
    ports:
      - 10102:80
    environment:
      DB_DSN: ${DB_DSN:-mysql:dbname=golly_db;host=db;port=3306}
      DB_USER: ${DB_USER:-golly_user}
      DB_PASS: ${DB_PASS:-golly_pass}
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-golly_db}
      MYSQL_USER: ${MYSQL_USER:-golly_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-golly_pass}
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local
